# Import Library

In [27]:
import pandas as pd

# Data Understanding
Dataset movie_metadata adalah dataset IMDB movie yang berisi 5000 baris dengan 28 kolom, dataset di unduh dari website Kaggle. Kita akan mencoba membuat sistem rekomendasi film kepada Users sesuai genre, jika sebelumya Users menonton film dengan genre Horror maka sistem akan merekomendasikan kepada Users pilihan berbagai film bergenre Horror

In [28]:
movie_data = pd.read_csv('movie_metadata.csv')
movie_data

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

Kita lihat di atas jumlah total data kita adalah 5043 baris dengan 28 kolom, kemudian kita akan mencari tau info lebih detail data dengan fungsi info().

# Univariate Exploratory

In [29]:
movie_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5031 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

Setelah kita jalankan dengan fungsi info(), kita bisa melihat semua variable pada dataser. Di dalamnya terdiri 13 tipe data **Float**, 3 tipe data **integer**, dan 12 tipe data **Object**.

In [30]:
movie_data.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

Kemudian kita mencari tau apakah seluruh data memiliki Missing Value di dalamnya, setelah di cek dengan fungsi isnull().sum() lumayan banyak variable yang memiliki Missing Value.

In [31]:
movie_data.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

Kita juga akan melihat lebih detail lagi dataset kita menggunakan fungsi describe(). terlihat bermacam-macam nilai pada variable dataset kita, namun karena kita akan membuat sistem rekomendasi film berdasarkan genre, kita tidak perlu banyak variable. Kita akan mengambil variable yang di butuhkan saja yaitu, genres, movie_title, num_user_for_reviews.

In [32]:
drop = ['color', 'director_name', 'num_critic_for_reviews', 'duration', 'director_facebook_likes',
                  'actor_3_facebook_likes', 'actor_2_name', 'actor_1_facebook_likes', 'gross', 'actor_1_name',
                  'num_voted_users', 'cast_total_facebook_likes', 'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
                  'movie_imdb_link', 'language', 'country', 'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
                  'imdb_score', 'aspect_ratio', 'movie_facebook_likes']

movie_data.drop(drop, axis=1, inplace=True)

Kita membuat variable drop untuk membuang banyak atribut di dalam dataset kita, dengan begitu dataset kita menjadi sangat simple tapi tetap berfungsi dengan baik.

Setelah variable drop dengan isi atribute yang ingin kita buang telah di buat, maka kita juga akan menghapus variable tersebut dari dataset menggunakan fungsi drop().

In [33]:
movie_data

,genres,movie_title,num_user_for_reviews
0,Action|Adventure|Fantasy|Sci-Fi,Avatar,3054.0
1,Action|Adventure|Fantasy,Pirates of the Caribbean: At World's End,1238.0
2,Action|Adventure|Thriller,Spectre,994.0
3,Action|Thriller,The Dark Knight Rises,2701.0
4,Documentary,Star Wars: Episode VII - The Force Awakens ...,NaN
...,...,...,...
5038,Comedy|Drama,Signed Sealed Delivered,6.0
5039,Crime|Drama|Mystery|Thriller,The Following,359.0
5040,Drama|Horror|Thriller,A Plague So Pleasant,3.0
5041,Comedy|Drama|Romance,Shanghai Calling,9.0
5042,Documentary,My Date with Drew,84.0

Kemudian kita cek dataset kita yang baru, terlihat seperti contoh di atas. Dataset jadi hanya 3 kolom yang tadinya berjumlah 28 kolom.


*   genres : Genre dari masing-masing film.
*   movie_title : Berisi judul-judul film.
*   num_user_for_reviews : Berisi review Users atas film tersebut.

In [34]:
print("Jumlah data rewview users adalah: ", len(movie_data.num_user_for_reviews.unique()))
print("Jumlah data nama movie adalah: ", len(movie_data.movie_title.unique()))
print("Jumlah data nama genre adalah: ", len(movie_data.genres.unique()))

Jumlah data rewview users adalah:  955
Jumlah data nama movie adalah:  4917
Jumlah data nama genre adalah:  914

Kita juga melihat panjang dari data dengan fungsi unique() agar menghindari data dengan hitungan duplikat.

# Data Preparation

Kita tidak melakukan tahap Data Preprocessing karena kita hanya memiliki satu file utuh, kita tidak melakukan penggabungan data pada kasus ini. Jadi kita langsung mulai ke tahap Data Preparation

In [35]:
movie_data.isnull().sum()

genres                   0
movie_title              0
num_user_for_reviews    21
dtype: int64

Sebelumnya kita melihat pada data utuh banyak sekali kita mendapati Missing Value, namun kita juga akan memeriksanya kembali dengan fungsi yang sama.

Dan setelah data di pisah, kemudian kita melihat Missing Value pada data, terlihat hanya atribut num_user_for_reviews yang memiliki Missing Value dengan total Missing 21 baris.

In [36]:
movie_data = movie_data.dropna()

Kita akan menghapus data Missing tersebut dengan fungsi dropna(), dengan fungsi tersebut kita bisa otomatis membuang baris pada kolom yang mengandung Missing Value.

In [37]:
movie_data.isnull().sum()

genres                  0
movie_title             0
num_user_for_reviews    0
dtype: int64

Setelah kita cek kembali data kita dengan isnull().sum(), data kita telah bersih dari Missing Value atau nilai kosong.

In [38]:
# Mengurutkan movie_data berdasarkan Review Users
movie_data = movie_data.sort_values('num_user_for_reviews', ascending=True)
movie_data

,genres,movie_title,num_user_for_reviews
2349,Biography|Drama|History,Ramanujan,1.0
4990,Documentary,Counting,1.0
4774,Comedy|Mystery|Thriller,The Sound and the Shadow,1.0
4771,Crime|Drama,The King of Najayo,1.0
4918,Comedy|Drama|Music,Theresa Is a Mother,1.0
...,...,...,...
240,Action|Adventure|Fantasy|Sci-Fi,Star Wars: Episode I - The Phantom Menace,3597.0
654,Action|Sci-Fi,The Matrix,3646.0
1937,Crime|Drama,The Shawshank Redemption,4144.0
66,Action|Crime|Drama|Thriller,The Dark Knight,4667.0
270,Action|Adventure|Drama|Fantasy,The Lord of the Rings: The Fellowship of the R...,5060.0

Setelah kita urutkan dengan fungsi sort_values(), bisa dilihat pada kolom num_user_for_reviews bahwa data di urutkan dari yang terkecil hingga yang terbesar. 
Dengan review yang paling sedikit sebanyak 1 sampai yang terbanyak yaitu 5060 review

In [39]:
len(movie_data.num_user_for_reviews.unique())

954

Kita coba cek data kita dengan memfilterya dengan unique(), jumlah nya adalah 954.

In [40]:
movie_data = movie_data.drop_duplicates('num_user_for_reviews')
movie_data

,genres,movie_title,num_user_for_reviews
2349,Biography|Drama|History,Ramanujan,1.0
206,Fantasy,Harry Potter and the Deathly Hallows: Part I,2.0
4201,Drama,Valley of the Heart's Delight,3.0
4711,Mystery|Thriller,Arnolds Park,4.0
4782,Action,Diamond Ruff,5.0
...,...,...,...
240,Action|Adventure|Fantasy|Sci-Fi,Star Wars: Episode I - The Phantom Menace,3597.0
654,Action|Sci-Fi,The Matrix,3646.0
1937,Crime|Drama,The Shawshank Redemption,4144.0
66,Action|Crime|Drama|Thriller,The Dark Knight,4667.0
270,Action|Adventure|Drama|Fantasy,The Lord of the Rings: The Fellowship of the R...,5060.0

Setelah itu kita akan menghapus juga data agar tidak memiliki duplikat data, kita menghapuskan data berdasarkan review users.

In [41]:
# konversi data series menjadi list

genres = movie_data['genres'].tolist()

movie = movie_data['movie_title'].tolist()

review_user = movie_data['num_user_for_reviews'].tolist()

Selanjutnya kita mengkonversikan data kita menjadi data list, dengan fungsi tolist() data kita akan di jadikan data list.

In [42]:
print(len(genres))
print(len(movie))
print(len(review_user))

954
954
954

Kita juga ingin cek jumlah total data kita dari masing-masing atribut, setiap atribute memiliki jumlah yang sama yaitu 954, Bagus!

In [43]:
movie

['Ramanujan\xa0',
 'Harry Potter and the Deathly Hallows: Part I\xa0',
 "Valley of the Heart's Delight\xa0",
 'Arnolds Park\xa0',
 'Diamond Ruff\xa0',
 'House at the End of the Drive\xa0',
 'Hidden Away\xa0',
 'Tiger Orange\xa0',
 'The Helix... Loaded\xa0',
 '3 Strikes\xa0',
 'Hansel & Gretel Get Baked\xa0',
 'Restless\xa0',
 'Green Street 3: Never Back Down\xa0',
 'Chicken Tikka Masala\xa0',
 'On the Outs\xa0',
 'The Blue Room\xa0',
 'Unnatural\xa0',
 'Queen Crab\xa0',
 'The Magic Flute\xa0',
 'Detention of the Dead\xa0',
 'I Married a Strange Person!\xa0',
 "A Turtle's Tale: Sammy's Adventures\xa0",
 'Woman Thou Art Loosed\xa0',
 'Ira & Abby\xa0',
 'Gomorrah\xa0            ',
 "She's Gotta Have It\xa0",
 'Out of the Blue\xa0',
 'Shanghai Surprise\xa0',
 'The Valley of Decision\xa0',
 'Chocolate: Deep Dark Secrets\xa0',
 'Khiladi 786\xa0',
 'Hollywood Shuffle\xa0',
 'The Sisterhood of the Traveling Pants 2\xa0',
 'The Christmas Candle\xa0',
 'Aberdeen\xa0',
 'Benji\xa0',
 'Beyond the Lights\xa0',
 'The Basket\xa0',
 'Light It Up\xa0',
 'Blackthorn\xa0',
 'Keeping Up with the Steins\xa0',
 'The 41-Year-Old Virgin Who Knocked Up Sarah Marshall and Felt Superbad About It\xa0',
 'The Blood of Heroes\xa0',
 'Flame and Citron\xa0',
 'Two Evil Eyes\xa0',
 'A Farewell to Arms\xa0',
 'Black Rock\xa0',
 'Chain Letter\xa0',
 'Race\xa0',
 'The Wood\xa0',
 'Yu-Gi-Oh! Duel Monsters\xa0            ',
 'The Dark Hours\xa0',
 'See Spot Run\xa0',
 'Mad Money\xa0',
 'Miracles from Heaven\xa0',
 'Imaginary Heroes\xa0',
 'Black or White\xa0',
 'The Jungle Book 2\xa0',
 'Catch a Fire\xa0',
 'We Are Your Friends\xa0',
 'By the Sea\xa0',
 'Cargo\xa0',
 'Dancer, Texas Pop. 81\xa0',
 'Ultramarines: A Warhammer 40,000 Movie\xa0',
 "Donovan's Reef\xa0",
 'Foodfight!\xa0',
 'Life\xa0            ',
 'Blue Car\xa0',
 'Barbershop 2: Back in Business\xa0',
 'Jade\xa0',
 'Damnation Alley\xa0',
 'Step Up Revolution\xa0',
 'My Favorite Martian\xa0',
 'Miami Vice\xa0            ',
 'Charlie St. Cloud\xa0',
 'Hamlet 2\xa0',
 'Astro Boy\xa0',
 'The Business of Strangers\xa0',
 'Lilyhammer\xa0            ',
 'Beyond the Mat\xa0',
 'Rumble in the Bronx\xa0',
 'October Baby\xa0',
 'The Game Plan\xa0',
 "What's the Worst That Could Happen?\xa0",
 'Alexander and the Terrible, Horrible, No Good, Very Bad Day\xa0',
 'Next Stop Wonderland\xa0',
 'The Canyons\xa0',
 'My Name Is Bruce\xa0',
 'Salvador\xa0',
 'Robin and Marian\xa0',
 "Say It Isn't So\xa0",
 'The Claim\xa0',
 'A Thousand Words\xa0',
 'Chill Factor\xa0',
 'Beverly Hills Cop II\xa0',
 'Firestarter\xa0',
 'Mary Reilly\xa0',
 'Firefox\xa0',
 'The Nutty Professor\xa0',
 'Corky Romano\xa0',
 'The Prince\xa0',
 'High Anxiety\xa0',
 'My Summer of Love\xa0',
 'The Rocker\xa0',
 'Flirting with Disaster\xa0',
 'The BFG\xa0',
 'Serial Mom\xa0',
 'The Apparition\xa0',
 'Conan the Destroyer\xa0',
 'The Odd Life of Timothy Green\xa0',
 'Clockwatchers\xa0',
 'Jeff, Who Lives at Home\xa0',
 'Veronica Guerin\xa0',
 'I Am Love\xa0',
 'Away We Go\xa0',
 'Daddy Day Care\xa0',
 'Connie and Carla\xa0',
 '9½ Weeks\xa0',
 'Margaret\xa0',
 'Bloody Sunday\xa0',
 'Did You Hear About the Morgans?\xa0',
 'Northfork\xa0',
 "My Boss's Daughter\xa0",
 'The Great Beauty\xa0',
 'The Women\xa0',
 'The Lazarus Effect\xa0',
 'Dead Man Down\xa0',
 'Where the Truth Lies\xa0',
 'Chasing Liberty\xa0',
 'El Mariachi\xa0',
 'Hardball\xa0',
 'The Promise\xa0',
 'Brother\xa0',
 "The Huntsman: Winter's War\xa0",
 'A Man Apart\xa0',
 'Bambi\xa0',
 "Madea's Family Reunion\xa0",
 'Pale Rider\xa0',
 'DragonHeart\xa0',
 'Copycat\xa0',
 'Stake Land\xa0',
 'Pontypool\xa0',
 'Dangerous Liaisons\xa0',
 'Ponyo\xa0',
 'The Gambler\xa0',
 'The Shadow\xa0',
 'Joyeux Noel\xa0',
 'Shutter\xa0',
 'The Change-Up\xa0',
 'Like Crazy\xa0',
 'Mirrormask\xa0',
 'WarGames\xa0',
 'My Own Private Idaho\xa0',
 'Silent House\xa0',
 'Batman: The Movie\xa0',
 'Morning Glory\xa0',
 'Abandon\xa0',
 'Persepolis\xa0',
 'Survival of the Dead\xa0',
 'Little Voice\xa0',
 'Nixon\xa0',
 '8 Women\xa0',
 'Point Break\xa0',
 'The Vow\xa0',
 'Mr. Turner\xa0',
 'War\xa0',
 'The Replacement Killers\xa0',
 'Herbie Fully Loaded\xa0',
 'Crazy/Beautiful\xa0',
 'The Fisher King\xa0',
 'St. Vincent\xa0',
 'Aloha\xa0',
 'Lone Star\xa0',
 'Welcome to the Dollhouse\xa0',
 'The Good German\xa0',
 'ParaNorman\xa0',
 'Four Rooms\xa0',
 'Krull\xa0',
 'The Haunted Mansion\xa0',
 'Bulletproof Monk\xa0',
 'American Reunion\xa0',
 'Miracle at St. Anna\xa0',
 'Pink Flamingos\xa0',
 'Blended\xa0',
 'Kingpin\xa0',
 'Fantasia 2000\xa0',
 'Megamind\xa0',
 'The Boondock Saints II: All Saints Day\xa0',
 'Street Kings\xa0',
 'Jersey Boys\xa0',
 'Godsend\xa0',
 'This Is England\xa0',
 'The White Ribbon\xa0',
 'What a Girl Wants\xa0',
 'The Croods\xa0',
 'Radio\xa0',
 'In the Company of Men\xa0',
 'UHF\xa0',
 'We Own the Night\xa0',
 'Walk Hard: The Dewey Cox Story\xa0',
 'Deliver Us from Evil\xa0',
 'Diary of a Mad Black Woman\xa0',
 'My Super Ex-Girlfriend\xa0',
 'Snow White and the Seven Dwarfs\xa0',
 'Spy Kids\xa0',
 'Bee Movie\xa0',
 'A Walk Among the Tombstones\xa0',
 'The Shipping News\xa0',
 'I Spit on Your Grave\xa0',
 'R.I.P.D.\xa0',
 "Valentine's Day\xa0",
 'Bad Lieutenant: Port of Call New Orleans\xa0',
 'The Mask\xa0',
 'Seed of Chucky\xa0',
 'Swept Away\xa0',
 'Killer Joe\xa0',
 'Treasure Planet\xa0',
 'Breakdown\xa0',
 "A Hard Day's Night\xa0",
 'The Painted Veil\xa0',
 'Walking Tall\xa0',
 'The Wind That Shakes the Barley\xa0',
 'This Is It\xa0',
 'Harry Brown\xa0',
 'The Pacifier\xa0',
 'The Running Man\xa0',
 'Escape from L.A.\xa0',
 'Volver\xa0',
 'Curse of the Golden Flower\xa0',
 'Hobo with a Shotgun\xa0',
 'Out of the Furnace\xa0',
 'Exit Wounds\xa0',
 'Priest\xa0',
 'Donnie Brasco\xa0',
 'The Karate Kid\xa0',
 'The Book Thief\xa0',
 'Disturbing Behavior\xa0',
 "The Sorcerer's Apprentice\xa0",
 'A Very Long Engagement\xa0',
 'Where the Heart Is\xa0',
 'The Piano\xa0',
 'Josie and the Pussycats\xa0',
 'Dragonfly\xa0',
 'Ella Enchanted\xa0',
 'Mr. Smith Goes to Washington\xa0',
 'Blades of Glory\xa0',
 'Flyboys\xa0',
 "Don't Say a Word\xa0",
 'A Christmas Carol\xa0',
 "Don't Be Afraid of the Dark\xa0",
 'Chicken Little\xa0',
 'Latter Days\xa0',
 'Wrath of the Titans\xa0',
 'The Three Musketeers\xa0',
 'Grown Ups 2\xa0',
 'Gandhi\xa0',
 'Evan Almighty\xa0',
 'Patton\xa0',
 'Invictus\xa0',
 'Safety Not Guaranteed\xa0',
 'Mud\xa0',
 'The Cave\xa0',
 'For Your Eyes Only\xa0',
 'Jack and Jill\xa0',
 'The Hurricane\xa0',
 'The Best Exotic Marigold Hotel\xa0',
 'You Only Live Twice\xa0',
 'Along Came Polly\xa0',
 'Hercules\xa0',
 'The Fugitive\xa0',
 'Underworld: Awakening\xa0',
 'A Mighty Wind\xa0',
 'Red Tails\xa0',
 'Sweet November\xa0',
 'Return to Me\xa0',
 'Diamonds Are Forever\xa0',
 'Step Brothers\xa0',
 '21\xa0',
 'Coraline\xa0',
 'The French Connection\xa0',
 'Rachel Getting Married\xa0',
 'Supernova\xa0',
 'Blue Valentine\xa0',
 'The Marine\xa0',
 'Dumb and Dumber To\xa0',
 'Star Trek: First Contact\xa0',
 'Red State\xa0',
 'The Ides of March\xa0',
 'Jack Ryan: Shadow Recruit\xa0',
 'Super Mario Bros.\xa0',
 'The Kids Are All Right\xa0',
 'Secondhand Lions\xa0',
 'Shanghai Noon\xa0',
 'Mad Max 2: The Road Warrior\xa0',
 'Bad Teacher\xa0',
 'Legally Blonde 2: Red, White & Blonde\xa0',
 'Lions for Lambs\xa0',
 'Lars and the Real Girl\xa0',
 'The Return of the Living Dead\xa0',
 'The Princess Diaries\xa0',
 'Hail, Caesar!\xa0',
 'Unleashed\xa0',
 'Mama\xa0',
 'Home Alone\xa0',
 'Beetlejuice\xa0',
 'Steve Jobs\xa0',
 'The Last Temptation of Christ\xa0',
 'Waterworld\xa0',
 'The Omen\xa0',
 'Grown Ups\xa0',
 'All Is Lost\xa0',
 'Inside Llewyn Davis\xa0',
 'Don Jon\xa0',
 'Legion\xa0',
 'Jeepers Creepers II\xa0',
 'Jason Goes to Hell: The Final Friday\xa0',
 "Buffalo '66\xa0",
 'The Blues Brothers\xa0',
 'Marley & Me\xa0',
 'Doubt\xa0',
 'Cinderella\xa0',
 'Hereafter\xa0',
 'Saved!\xa0',
 'Cursed\xa0',
 'Space Cowboys\xa0',
 'The Way of the Gun\xa0',
 'Tomorrow Never Dies\xa0',
 'The Twilight Saga: Breaking Dawn - Part 2\xa0',
 "Howl's Moving Castle\xa0",
 'Big Trouble in Little China\xa0',
 'Diary of the Dead\xa0',
 'High Noon\xa0',
 'The Covenant\xa0',
 'Halloween: The Curse of Michael Myers\xa0',
 'Bully\xa0',
 'Conan the Barbarian\xa0',
 'Shooter\xa0',
 'Oculus\xa0',
 'Four Brothers\xa0',
 'Death to Smoochy\xa0',
 'Spanglish\xa0',
 "America's Sweethearts\xa0",
 'The Mexican\xa0',
 '21 Jump Street\xa0',
 'Whale Rider\xa0',
 'Scary Movie 3\xa0',
 'Red Planet\xa0',
 'The Ghost Writer\xa0',
 'Grease\xa0',
 'Unbroken\xa0',
 'Movie 43\xa0',
 'The Prince of Egypt\xa0',
 'Kung Fu Hustle\xa0',
 'Highlander: Endgame\xa0',
 'Rock of Ages\xa0',
 'How to Lose a Guy in 10 Days\xa0',
 'Jersey Girl\xa0',
 'Disaster Movie\xa0',
 'The Man from U.N.C.L.E.\xa0',
 'Amores Perros\xa0',
 'Bicentennial Man\xa0',
 'Michael Clayton\xa0',
 'Dragon Wars: D-War\xa0',
 'Glory\xa0',
 'Fast Five\xa0',
 'Lilo & Stitch\xa0',
 'In the Name of the King: A Dungeon Siege Tale\xa0',
 'Darkness Falls\xa0',
 'The Contender\xa0',
 'The Skeleton Key\xa0',
 'Friday the 13th Part III\xa0',
 'Speed\xa0',
 'The Tourist\xa0',
 'Shame\xa0',
 'The Box\xa0',
 'Moonrise Kingdom\xa0',
 'The Fast and the Furious: Tokyo Drift\xa0',
 'Heroes\xa0            ',
 'The Abyss\xa0',
 'I Heart Huckabees\xa0',
 'Facing the Giants\xa0',
 'Red Dawn\xa0',
 'Hostel: Part II\xa0',
 'Y Tu Mamá También\xa0',
 'Ali\xa0',
 'Changeling\xa0',
 'Feardotcom\xa0',
 'Boogeyman\xa0',
 'Secretary\xa0',
 'Toy Story\xa0',
 'Machete\xa0',
 'Not Another Teen Movie\xa0',
 'Rush Hour 2\xa0',
 'Twister\xa0',
 'Doomsday\xa0',
 'Neighbors\xa0',
 'Eastern Promises\xa0',
 'Enchanted\xa0',
 'The Ladykillers\xa0',
 "The World's End\xa0",
 'The Hangover Part II\xa0',
 'Vampires\xa0',
 'Old School\xa0',
 'The Master\xa0',
 'The Sound of Music\xa0',
 'The Lives of Others\xa0',
 'Kids\xa0',
 'Spotlight\xa0',
 'Baahubali: The Beginning\xa0',
 'Behind Enemy Lines\xa0',
 'Sherlock Holmes: A Game of Shadows\xa0',
 'Metropolis\xa0',
 'The Straight Story\xa0',
 'The Assassination of Jesse James by the Coward Robert Ford\xa0',
 'Capote\xa0',
 'Go\xa0',
 'Running Scared\xa0',
 'Lone Survivor\xa0',
 'The Queen\xa0',
 'Vantage Point\xa0',
 'Resident Evil: Retribution\xa0',
 'The Pink Panther\xa0',
 'Austin Powers: International Man of Mystery\xa0',
 'Das Boot\xa0',
 'Airplane!\xa0',
 'Meet the Fockers\xa0',
 'Sicko\xa0',
 'Akira\xa0',
 'The Counselor\xa0',
 'The Wolfman\xa0',
 'Big Hero 6\xa0',
 'Idiocracy\xa0',
 'Angels & Demons\xa0',
 'The Equalizer\xa0',
 'Talladega Nights: The Ballad of Ricky Bobby\xa0',
 'Hanna\xa0',
 'Tombstone\xa0',
 'Mission: Impossible - Rogue Nation\xa0',
 'Nacho Libre\xa0',
 'JFK\xa0',
 'The Green Hornet\xa0',
 'The Polar Express\xa0',
 'The Score\xa0',
 "Rosemary's Baby\xa0",
 'Jack Reacher\xa0',
 'Australia\xa0',
 'Monsters\xa0',
 'Up in the Air\xa0',
 'Prince of Persia: The Sands of Time\xa0',
 '25th Hour\xa0',
 'Seabiscuit\xa0',
 '50 First Dates\xa0',
 'Book of Shadows: Blair Witch 2\xa0',
 'The Machinist\xa0',
 'The Transporter\xa0',
 'Sicario\xa0',
 'Jackie Brown\xa0',
 'Frailty\xa0',
 'The Core\xa0',
 'Corpse Bride\xa0',
 'When a Stranger Calls\xa0',
 "Dude, Where's My Car?\xa0",
 'As Good as It Gets\xa0',
 'To Kill a Mockingbird\xa0',
 'Clerks II\xa0',
 'Ghost Ship\xa0',
 'The Family Stone\xa0',
 'Indiana Jones and the Last Crusade\xa0',
 'Thir13en Ghosts\xa0',
 'Dark Shadows\xa0',
 'Me, Myself & Irene\xa0',
 'Perfume: The Story of a Murderer\xa0',
 'The Holiday\xa0',
 'Pirates of the Caribbean: On Stranger Tides\xa0',
 'Bad Santa\xa0',
 'What the #$*! Do We (K)now!?\xa0',
 'Scream 2\xa0',
 'Teenage Mutant Ninja Turtles\xa0',
 'The Brothers Grimm\xa0',
 'Deep Impact\xa0',
 'Raging Bull\xa0',
 'Once Upon a Time in America\xa0',
 'Gods and Generals\xa0',
 'Erin Brockovich\xa0',
 'Happiness\xa0',
 'Chasing Amy\xa0',
 'The Mummy: Tomb of the Dragon Emperor\xa0',
 'Underworld: Evolution\xa0',
 'A Good Day to Die Hard\xa0',
 'The Bourne Legacy\xa0',
 'Beowulf\xa0',
 'The Game\xa0',
 'Lucky Number Slevin\xa0',
 'The Woman in Black\xa0',
 'In the Bedroom\xa0',
 'Oz the Great and Powerful\xa0',
 'Mission: Impossible - Ghost Protocol\xa0',
 'Brazil\xa0',
 'Salt\xa0',
 'E.T. the Extra-Terrestrial\xa0',
 'Tinker Tailor Soldier Spy\xa0',
 'Kung Pow: Enter the Fist\xa0',
 'The Virgin Suicides\xa0',
 'Scooby-Doo\xa0',
 'Scott Pilgrim vs. the World\xa0',
 'Lock, Stock and Two Smoking Barrels\xa0',
 'Indiana Jones and the Temple of Doom\xa0',
 'Good Night, and Good Luck.\xa0',
 'Captain Phillips\xa0',
 'Stranger Than Fiction\xa0',
 'The Pledge\xa0',
 'Grindhouse\xa0',
 'The Wizard of Oz\xa0',
 'G.I. Joe: The Rise of Cobra\xa0',
 'Eraserhead\xa0',
 'House on Haunted Hill\xa0',
 'Evil Dead II\xa0',
 'High Tension\xa0',
 'Wrong Turn\xa0',
 'From Hell\xa0',
 'Rocky\xa0',
 'Swordfish\xa0',
 'The Count of Monte Cristo\xa0',
 'The Godfather: Part III\xa0',
 'Robin Hood\xa0',
 'The Wrestler\xa0',
 'The Lake House\xa0',
 'Ant-Man\xa0',
 'Green Lantern\xa0',
 'Melancholia\xa0',
 'Nightcrawler\xa0',
 'Zombieland\xa0',
 'Mean Girls\xa0',
 'Superbad\xa0',
 "You've Got Mail\xa0",
 '21 Grams\xa0',
 'Three Kings\xa0',
 'Spring Breakers\xa0',
 'World Trade Center\xa0',
 'Once Upon a Time in the West\xa0',
 "Singin' in the Rain\xa0",
 'Dune\xa0',
 'Princess Mononoke\xa0',
 "Bridget Jones's Diary\xa0",
 'Ronin\xa0',
 'House of Wax\xa0',
 'Tropic Thunder\xa0',
 'Crossroads\xa0',
 'Night of the Living Dead\xa0',
 'Atonement\xa0',
 'Blade\xa0',
 'The Artist\xa0',
 'Cars\xa0',
 'Public Enemies\xa0',
 'Pi\xa0',
 '8MM\xa0',
 'Dredd\xa0',
 'Zodiac\xa0',
 'Hancock\xa0',
 'The Hunger Games: Mockingjay - Part 1\xa0',
 'From Dusk Till Dawn\xa0',
 'The Lovely Bones\xa0',
 'The Terminal\xa0',
 'Hellboy\xa0',
 'Seven Pounds\xa0',
 'Flightplan\xa0',
 'U-571\xa0',
 'Army of Darkness\xa0',
 'One Hour Photo\xa0',
 'Men in Black II\xa0',
 'The Imitation Game\xa0',
 'Groundhog Day\xa0',
 'Batman Returns\xa0',
 'Contact\xa0',
 'About Schmidt\xa0',
 'Date Movie\xa0',
 'Halloween: Resurrection\xa0',
 'The Time Machine\xa0',
 'Under the Skin\xa0',
 'Sky Captain and the World of Tomorrow\xa0',
 'What Dreams May Come\xa0',
 'Dawn of the Planet of the Apes\xa0',
 'Office Space\xa0',
 'The Punisher\xa0',
 'Ted\xa0',
 'Dark City\xa0',
 'Syriana\xa0',
 'The Hangover\xa0',
 'Chappie\xa0',
 'Hollow Man\xa0',
 'Now You See Me\xa0',
 'RoboCop\xa0',
 'The Devil Wears Prada\xa0',
 'The Life Aquatic with Steve Zissou\xa0',
 'Training Day\xa0',
 'Maleficent\xa0',
 "The King's Speech\xa0",
 'Clash of the Titans\xa0',
 'The Man from Earth\xa0',
 'Zero Dark Thirty\xa0',
 'Gattaca\xa0',
 'Deep Blue Sea\xa0',
 'The Black Dahlia\xa0',
 'The Illusionist\xa0',
 'Inside Man\xa0',
 'Star Wars: Episode VI - Return of the Jedi\xa0',
 'Fear and Loathing in Las Vegas\xa0',
 'The Godfather: Part II\xa0',
 'Insomnia\xa0',
 "Bram Stoker's Dracula\xa0",
 'The Lion King\xa0',
 'Exodus: Gods and Kings\xa0',
 "A Knight's Tale\xa0",
 'Pay It Forward\xa0',
 'Enemy at the Gates\xa0',
 'Irreversible\xa0',
 'TRON: Legacy\xa0',
 'Epic Movie\xa0',
 'Catch Me If You Can\xa0',
 'A Nightmare on Elm Street\xa0',
 'This Is the End\xa0',
 'The New World\xa0',
 'Resident Evil: Apocalypse\xa0',
 'Jason X\xa0',
 'Final Destination\xa0',
 'The Cell\xa0',
 'Hugo\xa0',
 'Captain America: The First Avenger\xa0',
 'Ghost Rider\xa0',
 'Good Will Hunting\xa0',
 'The World Is Not Enough\xa0',
 'Master and Commander: The Far Side of the World\xa0',
 'Click\xa0',
 'Hot Fuzz\xa0',
 'Man on Fire\xa0',
 'Drag Me to Hell\xa0',
 'Silver Linings Playbook\xa0',
 '12 Years a Slave\xa0',
 'The Social Network\xa0',
 'Olympus Has Fallen\xa0',
 'Team America: World Police\xa0',
 'Fury\xa0',
 'Meet Joe Black\xa0',
 'Up\xa0',
 "It's a Wonderful Life\xa0",
 'Run Lola Run\xa0',
 'Adaptation.\xa0',
 'The Lone Ranger\xa0',
 '28 Weeks Later\xa0',
 'Identity\xa0',
 'The Princess Bride\xa0',
 'Jupiter Ascending\xa0',
 'Die Hard\xa0',
 'Iron Man 2\xa0',
 'True Grit\xa0',
 'Snatch\xa0',
 'Whiplash\xa0',
 'Toy Story 3\xa0',
 'Scream 3\xa0',
 'Match Point\xa0',
 'Alice in Wonderland\xa0',
 'xXx\xa0',
 'Thor\xa0',
 'The Evil Dead\xa0',
 'Edge of Tomorrow\xa0',
 'The Fifth Element\xa0',
 'After Earth\xa0',
 'An American Haunting\xa0',
 'Her\xa0',
 'Cruel Intentions\xa0',
 'American Hustle\xa0',
 'Insidious\xa0',
 'The Great Gatsby\xa0',
 'Rent\xa0',
 'The Grey\xa0',
 'My Big Fat Greek Wedding\xa0',
 'Into the Wild\xa0',
 'The Pianist\xa0',
 'The Simpsons Movie\xa0',
 'Red Dragon\xa0',
 'Raiders of the Lost Ark\xa0',
 'Inside Out\xa0',
 'Alien 3\xa0',
 'The Perfect Storm\xa0',
 'The Good, the Bad and the Ugly\xa0',
 'Warcraft\xa0',
 'Live Free or Die Hard\xa0',
 'Austin Powers: The Spy Who Shagged Me\xa0',
 'The League of Extraordinary Gentlemen\xa0',
 'Final Fantasy: The Spirits Within\xa0',
 'I, Robot\xa0',
 'Knowing\xa0',
 'Austin Powers in Goldmember\xa0',
 'Mr. & Mrs. Smith\xa0',
 'The Aviator\xa0',
 'Battle Los Angeles\xa0',
 'Kick-Ass\xa0',
 'The Hobbit: The Battle of the Five Armies\xa0',
 'Pitch Black\xa0',
 'The Bourne Supremacy\xa0',
 'The Conjuring\xa0',
 'Oldboy\xa0',
 'Doom\xa0',
 'Walk the Line\xa0',
 'Big Fish\xa0',
 'Batman\xa0',
 'The Bourne Ultimatum\xa0',
 'Almost Famous\xa0',
 'Lara Croft: Tomb Raider\xa0',
 'The Texas Chain Saw Massacre\xa0',
 'Cloud Atlas\xa0',
 'Ultraviolet\xa0',
 'Sideways\xa0',
 'Boyhood\xa0',
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb\xa0',
 'Being John Malkovich\xa0',
 'Hero\xa0',
 'Star Trek: Nemesis\xa0',
 "Ocean's Eleven\xa0",
 'Super 8\xa0',
 'Panic Room\xa0',
 'Scarface\xa0',
 'The Hills Have Eyes\xa0',
 'Independence Day\xa0',
 'Event Horizon\xa0',
 'Harry Potter and the Chamber of Secrets\xa0',
 'Shaun of the Dead\xa0',
 'O Brother, Where Art Thou?\xa0',
 'Saw II\xa0',
 'Finding Nemo\xa0',
 'Terminator Genisys\xa0',
 'Scream\xa0',
 'Gran Torino\xa0',
 'The Hurt Locker\xa0',
 'The Truman Show\xa0',
 'Taxi Driver\xa0',
 'Freddy vs. Jason\xa0',
 'Punch-Drunk Love\xa0',
 'Little Miss Sunshine\xa0',
 'The Mummy Returns\xa0',
 'Oblivion\xa0',
 'Jurassic Park\xa0',
 'The Island\xa0',
 'Star Wars: Episode V - The Empire Strikes Back\xa0',
 'Spirited Away\xa0',
 'Closer\xa0',
 'Frozen\xa0',
 'Babel\xa0',
 'The Thing\xa0',
 'The Fountain\xa0',
 'Open Water\xa0',
 'Transformers: Age of Extinction\xa0',
 'The Twilight Saga: New Moon\xa0',
 'House of 1000 Corpses\xa0',
 'The Last Samurai\xa0',
 'Reservoir Dogs\xa0',
 'Kill Bill: Vol. 2\xa0',
 'Kingdom of Heaven\xa0',
 'Skyline\xa0',
 'Shrek\xa0',
 'Mission to Mars\xa0',
 'The Hobbit: The Desolation of Smaug\xa0',
 'Jaws\xa0',
 'Shutter Island\xa0',
 'Suicide Squad\xa0',
 'Harry Potter and the Half-Blood Prince\xa0',
 'Taken\xa0',
 'The Tree of Life\xa0',
 'Garden State\xa0',
 'Terminator 2: Judgment Day\xa0',
 'Jeepers Creepers\xa0',
 'The Cabin in the Woods\xa0',
 'The Fast and the Furious\xa0',
 'Goodfellas\xa0',
 'Spectre\xa0',
 'World War Z\xa0',
 'Aliens vs. Predator: Requiem\xa0',
 'Love Actually\xa0',
 'Road to Perdition\xa0',
 'Dogma\xa0',
 'Chicago\xa0',
 'The Hateful Eight\xa0',
 'Captain America: Civil War\xa0',
 'The Martian\xa0',
 'The Deer Hunter\xa0',
 'The Big Lebowski\xa0',
 'Snakes on a Plane\xa0',
 'Psycho\xa0',
 'Apocalypto\xa0',
 'Starship Troopers\xa0',
 'Cast Away\xa0',
 "The Hitchhiker's Guide to the Galaxy\xa0",
 '2012\xa0',
 'Dawn of the Dead\xa0',
 'Pride & Prejudice\xa0',
 'American Psycho\xa0',
 'Braveheart\xa0',
 'The Mist\xa0',
 'The Amazing Spider-Man 2\xa0',
 'Aliens\xa0',
 'Se7en\xa0',
 "Pan's Labyrinth\xa0",
 'Guardians of the Galaxy\xa0',
 'The Descent\xa0',
 'Birdman or (The Unexpected Virtue of Ignorance)\xa0',
 'Black Hawk Down\xa0',
 'Pacific Rim\xa0',
 'There Will Be Blood\xa0',
 'Harry Potter and the Order of the Phoenix\xa0',
 'The Others\xa0',
 'Alien\xa0',
 'The Notebook\xa0',
 'Avengers: Age of Ultron\xa0',
 'Casablanca\xa0',
 'A History of Violence\xa0',
 'Gone Girl\xa0',
 'Equilibrium\xa0',
 'Resident Evil\xa0',
 'Black Swan\xa0',
 'The Patriot\xa0',
 'The Day After Tomorrow\xa0',
 'Gangs of New York\xa0',
 'Blade Runner\xa0',

Namun kita memiliki problem pada kasus kita saat membuat sistem rekomendasi, yaitu tiba-tiba data film kita setelah di jadikan list menjadi berubah. Bisa kita lihat di atas nama setiap film menjadi ada tambahan di belakangnya yaitu **\ax0**.

Ini akan akan sangat mengganggu ketika kita ingin mencari rekomendasi film yang serupa berdasarkan genre, karena kita harus memasukan **\ax0** setelah menulis judul film, kita tidak menginginkan itu.

Jadi kita putuhkan untuk menghapus tulisan tersebut dari data film kita.

In [44]:
movie = list(map(lambda st: str.replace(st, "\xa0", ""), movie))
movie

['Ramanujan',
 'Harry Potter and the Deathly Hallows: Part I',
 "Valley of the Heart's Delight",
 'Arnolds Park',
 'Diamond Ruff',
 'House at the End of the Drive',
 'Hidden Away',
 'Tiger Orange',
 'The Helix... Loaded',
 '3 Strikes',
 'Hansel & Gretel Get Baked',
 'Restless',
 'Green Street 3: Never Back Down',
 'Chicken Tikka Masala',
 'On the Outs',
 'The Blue Room',
 'Unnatural',
 'Queen Crab',
 'The Magic Flute',
 'Detention of the Dead',
 'I Married a Strange Person!',
 "A Turtle's Tale: Sammy's Adventures",
 'Woman Thou Art Loosed',
 'Ira & Abby',
 'Gomorrah            ',
 "She's Gotta Have It",
 'Out of the Blue',
 'Shanghai Surprise',
 'The Valley of Decision',
 'Chocolate: Deep Dark Secrets',
 'Khiladi 786',
 'Hollywood Shuffle',
 'The Sisterhood of the Traveling Pants 2',
 'The Christmas Candle',
 'Aberdeen',
 'Benji',
 'Beyond the Lights',
 'The Basket',
 'Light It Up',
 'Blackthorn',
 'Keeping Up with the Steins',
 'The 41-Year-Old Virgin Who Knocked Up Sarah Marshall and Felt Superbad About It',
 'The Blood of Heroes',
 'Flame and Citron',
 'Two Evil Eyes',
 'A Farewell to Arms',
 'Black Rock',
 'Chain Letter',
 'Race',
 'The Wood',
 'Yu-Gi-Oh! Duel Monsters            ',
 'The Dark Hours',
 'See Spot Run',
 'Mad Money',
 'Miracles from Heaven',
 'Imaginary Heroes',
 'Black or White',
 'The Jungle Book 2',
 'Catch a Fire',
 'We Are Your Friends',
 'By the Sea',
 'Cargo',
 'Dancer, Texas Pop. 81',
 'Ultramarines: A Warhammer 40,000 Movie',
 "Donovan's Reef",
 'Foodfight!',
 'Life            ',
 'Blue Car',
 'Barbershop 2: Back in Business',
 'Jade',
 'Damnation Alley',
 'Step Up Revolution',
 'My Favorite Martian',
 'Miami Vice            ',
 'Charlie St. Cloud',
 'Hamlet 2',
 'Astro Boy',
 'The Business of Strangers',
 'Lilyhammer            ',
 'Beyond the Mat',
 'Rumble in the Bronx',
 'October Baby',
 'The Game Plan',
 "What's the Worst That Could Happen?",
 'Alexander and the Terrible, Horrible, No Good, Very Bad Day',
 'Next Stop Wonderland',
 'The Canyons',
 'My Name Is Bruce',
 'Salvador',
 'Robin and Marian',
 "Say It Isn't So",
 'The Claim',
 'A Thousand Words',
 'Chill Factor',
 'Beverly Hills Cop II',
 'Firestarter',
 'Mary Reilly',
 'Firefox',
 'The Nutty Professor',
 'Corky Romano',
 'The Prince',
 'High Anxiety',
 'My Summer of Love',
 'The Rocker',
 'Flirting with Disaster',
 'The BFG',
 'Serial Mom',
 'The Apparition',
 'Conan the Destroyer',
 'The Odd Life of Timothy Green',
 'Clockwatchers',
 'Jeff, Who Lives at Home',
 'Veronica Guerin',
 'I Am Love',
 'Away We Go',
 'Daddy Day Care',
 'Connie and Carla',
 '9½ Weeks',
 'Margaret',
 'Bloody Sunday',
 'Did You Hear About the Morgans?',
 'Northfork',
 "My Boss's Daughter",
 'The Great Beauty',
 'The Women',
 'The Lazarus Effect',
 'Dead Man Down',
 'Where the Truth Lies',
 'Chasing Liberty',
 'El Mariachi',
 'Hardball',
 'The Promise',
 'Brother',
 "The Huntsman: Winter's War",
 'A Man Apart',
 'Bambi',
 "Madea's Family Reunion",
 'Pale Rider',
 'DragonHeart',
 'Copycat',
 'Stake Land',
 'Pontypool',
 'Dangerous Liaisons',
 'Ponyo',
 'The Gambler',
 'The Shadow',
 'Joyeux Noel',
 'Shutter',
 'The Change-Up',
 'Like Crazy',
 'Mirrormask',
 'WarGames',
 'My Own Private Idaho',
 'Silent House',
 'Batman: The Movie',
 'Morning Glory',
 'Abandon',
 'Persepolis',
 'Survival of the Dead',
 'Little Voice',
 'Nixon',
 '8 Women',
 'Point Break',
 'The Vow',
 'Mr. Turner',
 'War',
 'The Replacement Killers',
 'Herbie Fully Loaded',
 'Crazy/Beautiful',
 'The Fisher King',
 'St. Vincent',
 'Aloha',
 'Lone Star',
 'Welcome to the Dollhouse',
 'The Good German',
 'ParaNorman',
 'Four Rooms',
 'Krull',
 'The Haunted Mansion',
 'Bulletproof Monk',
 'American Reunion',
 'Miracle at St. Anna',
 'Pink Flamingos',
 'Blended',
 'Kingpin',
 'Fantasia 2000',
 'Megamind',
 'The Boondock Saints II: All Saints Day',
 'Street Kings',
 'Jersey Boys',
 'Godsend',
 'This Is England',
 'The White Ribbon',
 'What a Girl Wants',
 'The Croods',
 'Radio',
 'In the Company of Men',
 'UHF',
 'We Own the Night',
 'Walk Hard: The Dewey Cox Story',
 'Deliver Us from Evil',
 'Diary of a Mad Black Woman',
 'My Super Ex-Girlfriend',
 'Snow White and the Seven Dwarfs',
 'Spy Kids',
 'Bee Movie',
 'A Walk Among the Tombstones',
 'The Shipping News',
 'I Spit on Your Grave',
 'R.I.P.D.',
 "Valentine's Day",
 'Bad Lieutenant: Port of Call New Orleans',
 'The Mask',
 'Seed of Chucky',
 'Swept Away',
 'Killer Joe',
 'Treasure Planet',
 'Breakdown',
 "A Hard Day's Night",
 'The Painted Veil',
 'Walking Tall',
 'The Wind That Shakes the Barley',
 'This Is It',
 'Harry Brown',
 'The Pacifier',
 'The Running Man',
 'Escape from L.A.',
 'Volver',
 'Curse of the Golden Flower',
 'Hobo with a Shotgun',
 'Out of the Furnace',
 'Exit Wounds',
 'Priest',
 'Donnie Brasco',
 'The Karate Kid',
 'The Book Thief',
 'Disturbing Behavior',
 "The Sorcerer's Apprentice",
 'A Very Long Engagement',
 'Where the Heart Is',
 'The Piano',
 'Josie and the Pussycats',
 'Dragonfly',
 'Ella Enchanted',
 'Mr. Smith Goes to Washington',
 'Blades of Glory',
 'Flyboys',
 "Don't Say a Word",
 'A Christmas Carol',
 "Don't Be Afraid of the Dark",
 'Chicken Little',
 'Latter Days',
 'Wrath of the Titans',
 'The Three Musketeers',
 'Grown Ups 2',
 'Gandhi',
 'Evan Almighty',
 'Patton',
 'Invictus',
 'Safety Not Guaranteed',
 'Mud',
 'The Cave',
 'For Your Eyes Only',
 'Jack and Jill',
 'The Hurricane',
 'The Best Exotic Marigold Hotel',
 'You Only Live Twice',
 'Along Came Polly',
 'Hercules',
 'The Fugitive',
 'Underworld: Awakening',
 'A Mighty Wind',
 'Red Tails',
 'Sweet November',
 'Return to Me',
 'Diamonds Are Forever',
 'Step Brothers',
 '21',
 'Coraline',
 'The French Connection',
 'Rachel Getting Married',
 'Supernova',
 'Blue Valentine',
 'The Marine',
 'Dumb and Dumber To',
 'Star Trek: First Contact',
 'Red State',
 'The Ides of March',
 'Jack Ryan: Shadow Recruit',
 'Super Mario Bros.',
 'The Kids Are All Right',
 'Secondhand Lions',
 'Shanghai Noon',
 'Mad Max 2: The Road Warrior',
 'Bad Teacher',
 'Legally Blonde 2: Red, White & Blonde',
 'Lions for Lambs',
 'Lars and the Real Girl',
 'The Return of the Living Dead',
 'The Princess Diaries',
 'Hail, Caesar!',
 'Unleashed',
 'Mama',
 'Home Alone',
 'Beetlejuice',
 'Steve Jobs',
 'The Last Temptation of Christ',
 'Waterworld',
 'The Omen',
 'Grown Ups',
 'All Is Lost',
 'Inside Llewyn Davis',
 'Don Jon',
 'Legion',
 'Jeepers Creepers II',
 'Jason Goes to Hell: The Final Friday',
 "Buffalo '66",
 'The Blues Brothers',
 'Marley & Me',
 'Doubt',
 'Cinderella',
 'Hereafter',
 'Saved!',
 'Cursed',
 'Space Cowboys',
 'The Way of the Gun',
 'Tomorrow Never Dies',
 'The Twilight Saga: Breaking Dawn - Part 2',
 "Howl's Moving Castle",
 'Big Trouble in Little China',
 'Diary of the Dead',
 'High Noon',
 'The Covenant',
 'Halloween: The Curse of Michael Myers',
 'Bully',
 'Conan the Barbarian',
 'Shooter',
 'Oculus',
 'Four Brothers',
 'Death to Smoochy',
 'Spanglish',
 "America's Sweethearts",
 'The Mexican',
 '21 Jump Street',
 'Whale Rider',
 'Scary Movie 3',
 'Red Planet',
 'The Ghost Writer',
 'Grease',
 'Unbroken',
 'Movie 43',
 'The Prince of Egypt',
 'Kung Fu Hustle',
 'Highlander: Endgame',
 'Rock of Ages',
 'How to Lose a Guy in 10 Days',
 'Jersey Girl',
 'Disaster Movie',
 'The Man from U.N.C.L.E.',
 'Amores Perros',
 'Bicentennial Man',
 'Michael Clayton',
 'Dragon Wars: D-War',
 'Glory',
 'Fast Five',
 'Lilo & Stitch',
 'In the Name of the King: A Dungeon Siege Tale',
 'Darkness Falls',
 'The Contender',
 'The Skeleton Key',
 'Friday the 13th Part III',
 'Speed',
 'The Tourist',
 'Shame',
 'The Box',
 'Moonrise Kingdom',
 'The Fast and the Furious: Tokyo Drift',
 'Heroes            ',
 'The Abyss',
 'I Heart Huckabees',
 'Facing the Giants',
 'Red Dawn',
 'Hostel: Part II',
 'Y Tu Mamá También',
 'Ali',
 'Changeling',
 'Feardotcom',
 'Boogeyman',
 'Secretary',
 'Toy Story',
 'Machete',
 'Not Another Teen Movie',
 'Rush Hour 2',
 'Twister',
 'Doomsday',
 'Neighbors',
 'Eastern Promises',
 'Enchanted',
 'The Ladykillers',
 "The World's End",
 'The Hangover Part II',
 'Vampires',
 'Old School',
 'The Master',
 'The Sound of Music',
 'The Lives of Others',
 'Kids',
 'Spotlight',
 'Baahubali: The Beginning',
 'Behind Enemy Lines',
 'Sherlock Holmes: A Game of Shadows',
 'Metropolis',
 'The Straight Story',
 'The Assassination of Jesse James by the Coward Robert Ford',
 'Capote',
 'Go',
 'Running Scared',
 'Lone Survivor',
 'The Queen',
 'Vantage Point',
 'Resident Evil: Retribution',
 'The Pink Panther',
 'Austin Powers: International Man of Mystery',
 'Das Boot',
 'Airplane!',
 'Meet the Fockers',
 'Sicko',
 'Akira',
 'The Counselor',
 'The Wolfman',
 'Big Hero 6',
 'Idiocracy',
 'Angels & Demons',
 'The Equalizer',
 'Talladega Nights: The Ballad of Ricky Bobby',
 'Hanna',
 'Tombstone',
 'Mission: Impossible - Rogue Nation',
 'Nacho Libre',
 'JFK',
 'The Green Hornet',
 'The Polar Express',
 'The Score',
 "Rosemary's Baby",
 'Jack Reacher',
 'Australia',
 'Monsters',
 'Up in the Air',
 'Prince of Persia: The Sands of Time',
 '25th Hour',
 'Seabiscuit',
 '50 First Dates',
 'Book of Shadows: Blair Witch 2',
 'The Machinist',
 'The Transporter',
 'Sicario',
 'Jackie Brown',
 'Frailty',
 'The Core',
 'Corpse Bride',
 'When a Stranger Calls',
 "Dude, Where's My Car?",
 'As Good as It Gets',
 'To Kill a Mockingbird',
 'Clerks II',
 'Ghost Ship',
 'The Family Stone',
 'Indiana Jones and the Last Crusade',
 'Thir13en Ghosts',
 'Dark Shadows',
 'Me, Myself & Irene',
 'Perfume: The Story of a Murderer',
 'The Holiday',
 'Pirates of the Caribbean: On Stranger Tides',
 'Bad Santa',
 'What the #$*! Do We (K)now!?',
 'Scream 2',
 'Teenage Mutant Ninja Turtles',
 'The Brothers Grimm',
 'Deep Impact',
 'Raging Bull',
 'Once Upon a Time in America',
 'Gods and Generals',
 'Erin Brockovich',
 'Happiness',
 'Chasing Amy',
 'The Mummy: Tomb of the Dragon Emperor',
 'Underworld: Evolution',
 'A Good Day to Die Hard',
 'The Bourne Legacy',
 'Beowulf',
 'The Game',
 'Lucky Number Slevin',
 'The Woman in Black',
 'In the Bedroom',
 'Oz the Great and Powerful',
 'Mission: Impossible - Ghost Protocol',
 'Brazil',
 'Salt',
 'E.T. the Extra-Terrestrial',
 'Tinker Tailor Soldier Spy',
 'Kung Pow: Enter the Fist',
 'The Virgin Suicides',
 'Scooby-Doo',
 'Scott Pilgrim vs. the World',
 'Lock, Stock and Two Smoking Barrels',
 'Indiana Jones and the Temple of Doom',
 'Good Night, and Good Luck.',
 'Captain Phillips',
 'Stranger Than Fiction',
 'The Pledge',
 'Grindhouse',
 'The Wizard of Oz',
 'G.I. Joe: The Rise of Cobra',
 'Eraserhead',
 'House on Haunted Hill',
 'Evil Dead II',
 'High Tension',
 'Wrong Turn',
 'From Hell',
 'Rocky',
 'Swordfish',
 'The Count of Monte Cristo',
 'The Godfather: Part III',
 'Robin Hood',
 'The Wrestler',
 'The Lake House',
 'Ant-Man',
 'Green Lantern',
 'Melancholia',
 'Nightcrawler',
 'Zombieland',
 'Mean Girls',
 'Superbad',
 "You've Got Mail",
 '21 Grams',
 'Three Kings',
 'Spring Breakers',
 'World Trade Center',
 'Once Upon a Time in the West',
 "Singin' in the Rain",
 'Dune',
 'Princess Mononoke',
 "Bridget Jones's Diary",
 'Ronin',
 'House of Wax',
 'Tropic Thunder',
 'Crossroads',
 'Night of the Living Dead',
 'Atonement',
 'Blade',
 'The Artist',
 'Cars',
 'Public Enemies',
 'Pi',
 '8MM',
 'Dredd',
 'Zodiac',
 'Hancock',
 'The Hunger Games: Mockingjay - Part 1',
 'From Dusk Till Dawn',
 'The Lovely Bones',
 'The Terminal',
 'Hellboy',
 'Seven Pounds',
 'Flightplan',
 'U-571',
 'Army of Darkness',
 'One Hour Photo',
 'Men in Black II',
 'The Imitation Game',
 'Groundhog Day',
 'Batman Returns',
 'Contact',
 'About Schmidt',
 'Date Movie',
 'Halloween: Resurrection',
 'The Time Machine',
 'Under the Skin',
 'Sky Captain and the World of Tomorrow',
 'What Dreams May Come',
 'Dawn of the Planet of the Apes',
 'Office Space',
 'The Punisher',
 'Ted',
 'Dark City',
 'Syriana',
 'The Hangover',
 'Chappie',
 'Hollow Man',
 'Now You See Me',
 'RoboCop',
 'The Devil Wears Prada',
 'The Life Aquatic with Steve Zissou',
 'Training Day',
 'Maleficent',
 "The King's Speech",
 'Clash of the Titans',
 'The Man from Earth',
 'Zero Dark Thirty',
 'Gattaca',
 'Deep Blue Sea',
 'The Black Dahlia',
 'The Illusionist',
 'Inside Man',
 'Star Wars: Episode VI - Return of the Jedi',
 'Fear and Loathing in Las Vegas',
 'The Godfather: Part II',
 'Insomnia',
 "Bram Stoker's Dracula",
 'The Lion King',
 'Exodus: Gods and Kings',
 "A Knight's Tale",
 'Pay It Forward',
 'Enemy at the Gates',
 'Irreversible',
 'TRON: Legacy',
 'Epic Movie',
 'Catch Me If You Can',
 'A Nightmare on Elm Street',
 'This Is the End',
 'The New World',
 'Resident Evil: Apocalypse',
 'Jason X',
 'Final Destination',
 'The Cell',
 'Hugo',
 'Captain America: The First Avenger',
 'Ghost Rider',
 'Good Will Hunting',
 'The World Is Not Enough',
 'Master and Commander: The Far Side of the World',
 'Click',
 'Hot Fuzz',
 'Man on Fire',
 'Drag Me to Hell',
 'Silver Linings Playbook',
 '12 Years a Slave',
 'The Social Network',
 'Olympus Has Fallen',
 'Team America: World Police',
 'Fury',
 'Meet Joe Black',
 'Up',
 "It's a Wonderful Life",
 'Run Lola Run',
 'Adaptation.',
 'The Lone Ranger',
 '28 Weeks Later',
 'Identity',
 'The Princess Bride',
 'Jupiter Ascending',
 'Die Hard',
 'Iron Man 2',
 'True Grit',
 'Snatch',
 'Whiplash',
 'Toy Story 3',
 'Scream 3',
 'Match Point',
 'Alice in Wonderland',
 'xXx',
 'Thor',
 'The Evil Dead',
 'Edge of Tomorrow',
 'The Fifth Element',
 'After Earth',
 'An American Haunting',
 'Her',
 'Cruel Intentions',
 'American Hustle',
 'Insidious',
 'The Great Gatsby',
 'Rent',
 'The Grey',
 'My Big Fat Greek Wedding',
 'Into the Wild',
 'The Pianist',
 'The Simpsons Movie',
 'Red Dragon',
 'Raiders of the Lost Ark',
 'Inside Out',
 'Alien 3',
 'The Perfect Storm',
 'The Good, the Bad and the Ugly',
 'Warcraft',
 'Live Free or Die Hard',
 'Austin Powers: The Spy Who Shagged Me',
 'The League of Extraordinary Gentlemen',
 'Final Fantasy: The Spirits Within',
 'I, Robot',
 'Knowing',
 'Austin Powers in Goldmember',
 'Mr. & Mrs. Smith',
 'The Aviator',
 'Battle Los Angeles',
 'Kick-Ass',
 'The Hobbit: The Battle of the Five Armies',
 'Pitch Black',
 'The Bourne Supremacy',
 'The Conjuring',
 'Oldboy',
 'Doom',
 'Walk the Line',
 'Big Fish',
 'Batman',
 'The Bourne Ultimatum',
 'Almost Famous',
 'Lara Croft: Tomb Raider',
 'The Texas Chain Saw Massacre',
 'Cloud Atlas',
 'Ultraviolet',
 'Sideways',
 'Boyhood',
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
 'Being John Malkovich',
 'Hero',
 'Star Trek: Nemesis',
 "Ocean's Eleven",
 'Super 8',
 'Panic Room',
 'Scarface',
 'The Hills Have Eyes',
 'Independence Day',
 'Event Horizon',
 'Harry Potter and the Chamber of Secrets',
 'Shaun of the Dead',
 'O Brother, Where Art Thou?',
 'Saw II',
 'Finding Nemo',
 'Terminator Genisys',
 'Scream',
 'Gran Torino',
 'The Hurt Locker',
 'The Truman Show',
 'Taxi Driver',
 'Freddy vs. Jason',
 'Punch-Drunk Love',
 'Little Miss Sunshine',
 'The Mummy Returns',
 'Oblivion',
 'Jurassic Park',
 'The Island',
 'Star Wars: Episode V - The Empire Strikes Back',
 'Spirited Away',
 'Closer',
 'Frozen',
 'Babel',
 'The Thing',
 'The Fountain',
 'Open Water',
 'Transformers: Age of Extinction',
 'The Twilight Saga: New Moon',
 'House of 1000 Corpses',
 'The Last Samurai',
 'Reservoir Dogs',
 'Kill Bill: Vol. 2',
 'Kingdom of Heaven',
 'Skyline',
 'Shrek',
 'Mission to Mars',
 'The Hobbit: The Desolation of Smaug',
 'Jaws',
 'Shutter Island',
 'Suicide Squad',
 'Harry Potter and the Half-Blood Prince',
 'Taken',
 'The Tree of Life',
 'Garden State',
 'Terminator 2: Judgment Day',
 'Jeepers Creepers',
 'The Cabin in the Woods',
 'The Fast and the Furious',
 'Goodfellas',
 'Spectre',
 'World War Z',
 'Aliens vs. Predator: Requiem',
 'Love Actually',
 'Road to Perdition',
 'Dogma',
 'Chicago',
 'The Hateful Eight',
 'Captain America: Civil War',
 'The Martian',
 'The Deer Hunter',
 'The Big Lebowski',
 'Snakes on a Plane',
 'Psycho',
 'Apocalypto',
 'Starship Troopers',
 'Cast Away',
 "The Hitchhiker's Guide to the Galaxy",
 '2012',
 'Dawn of the Dead',
 'Pride & Prejudice',
 'American Psycho',
 'Braveheart',
 'The Mist',
 'The Amazing Spider-Man 2',
 'Aliens',
 'Se7en',
 "Pan's Labyrinth",
 'Guardians of the Galaxy',
 'The Descent',
 'Birdman or (The Unexpected Virtue of Ignorance)',
 'Black Hawk Down',
 'Pacific Rim',
 'There Will Be Blood',
 'Harry Potter and the Order of the Phoenix',
 'The Others',
 'Alien',
 'The Notebook',
 'Avengers: Age of Ultron',
 'Casablanca',
 'A History of Violence',
 'Gone Girl',
 'Equilibrium',
 'Resident Evil',
 'Black Swan',
 'The Patriot',
 'The Day After Tomorrow',
 'Gangs of New York',
 'Blade Runner',
 'A Beautiful Mind',
 'The Usual Suspects',
 'Die Another Day',
 'Iron Man 3',
 'The Revenant',
 'Paranormal Activity',
 'Halloween',
 'Django Unchained',
 'Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan',
 'Children of Men',
 'Ghostbusters',
 'The Amazing Spider-Man',
 'Watchmen',
 'Jurassic Park III',
 "Pirates of the Caribbean: At World's End",
 'Noah',
 'Quantum of Solace',
 'Vanilla Sky',
 'District 9',
 'Drive',
 "Schindler's List",
 'AVP: Alien vs. Predator',
 'Jurassic World',
 'Spider-Man 2',
 'Battlefield Earth',
 'Amélie',
 'The Shining',
 'Minority Report',
 'Unbreakable',
 'Fifty Shades of Grey',
 'Charlie and the Chocolate Factory',
 'The Hobbit: An Unexpected Journey',
 'Planet of the Apes',
 'The Green Mile',
 'The Last Airbender',
 'Alexander',
 'Forrest Gump',
 'X-Men',
 'I Am Legend',
 'Fahrenheit 9/11',
 'American History X',
 'Mission: Impossible II',
 'Magnolia',
 'Transformers: Revenge of the Fallen',
 '28 Days Later...',
 'Hulk',
 'The Thin Red Line',
 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
 'Star Wars: Episode IV - A New Hope',
 'Napoleon Dynamite',
 'Skyfall',
 'Eyes Wide Shut',
 'Harry Potter and the Prisoner of Azkaban',
 'Saw',
 'Eternal Sunshine of the Spotless Mind',
 'Hostel',
 'No Country for Old Men',
 'Inglourious Basterds',
 'Twilight',
 'Star Trek',
 "Harry Potter and the Sorcerer's Stone",
 'Mad Max: Fury Road',
 'Serenity',
 'Crash',
 'Crouching Tiger, Hidden Dragon',
 'Terminator 3: Rise of the Machines',
 'Eragon',
 'Troy',
 'The Avengers',
 'Sin City',
 '2001: A Space Odyssey',
 'Silent Hill',
 'Mulholland Drive',
 'Transformers',
 "Pirates of the Caribbean: Dead Man's Chest",
 'Lost in Translation',
 'Gravity',
 'Harry Potter and the Goblet of Fire',
 'Spider-Man 3',
 'X-Men: The Last Stand',
 'Requiem for a Dream',
 'The Hunger Games',
 'The Da Vinci Code',
 'Pearl Harbor',
 'The Village',
 'Spider-Man',
 'V for Vendetta',
 'The Phantom of the Opera',
 'Indiana Jones and the Kingdom of the Crystal Skull',
 'Memento',
 'The Sixth Sense',
 'Kill Bill: Vol. 1',
 'Donnie Darko',
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'The Matrix Revolutions',
 'A.I. Artificial Intelligence',
 'Cloverfield',
 'Pulp Fiction',
 'The Godfather',
 'Brokeback Mountain',
 'Saving Private Ryan',
 'Casino Royale',
 'Moulin Rouge!',
 'Prometheus',
 'Signs',
 'Superman Returns',
 'Gladiator',
 'The Lord of the Rings: The Two Towers',
 'Titanic',
 'Man of Steel',
 'King Kong',
 'Batman Begins',
 'The Dark Knight Rises',
 'American Beauty',
 'Interstellar',
 'War of the Worlds',
 'The Matrix Reloaded',
 'Inception',
 'The Passion of the Christ',
 'Fight Club',
 'Batman v Superman: Dawn of Justice',
 'Avatar',
 'The Lord of the Rings: The Return of the King',
 'Star Wars: Episode III - Revenge of the Sith',
 'The Blair Witch Project',
 'Star Wars: Episode II - Attack of the Clones',
 'Star Wars: Episode I - The Phantom Menace',
 'The Matrix',
 'The Shawshank Redemption',
 'The Dark Knight',
 'The Lord of the Rings: The Fellowship of the Ring']

Dengan lamda dan melakukan replace pada data film, kita sudah membuang tulisan yang mengganggu tersebut. Sekarang data kita sudah benar-benar bersih dari gangguan.

In [45]:
movie_new = pd.DataFrame({
    'review_users' : review_user,
    'movie' : movie,
    'genre' : genres
})
movie_new

,review_users,movie,genre
0,1.0,Ramanujan,Biography|Drama|History
1,2.0,Harry Potter and the Deathly Hallows: Part I,Fantasy
2,3.0,Valley of the Heart's Delight,Drama
3,4.0,Arnolds Park,Mystery|Thriller
4,5.0,Diamond Ruff,Action
...,...,...,...
949,3597.0,Star Wars: Episode I - The Phantom Menace,Action|Adventure|Fantasy|Sci-Fi
950,3646.0,The Matrix,Action|Sci-Fi
951,4144.0,The Shawshank Redemption,Crime|Drama
952,4667.0,The Dark Knight,Action|Crime|Drama|Thriller
953,5060.0,The Lord of the Rings: The Fellowship of the Ring,Action|Adventure|Drama|Fantasy

Selanjutnya kita akan membuat Dictionary dari data yang sudah kita perbaiki sebelumnya untuk menentukan key:value pada setiap atribut.

# Model Development with Content Based Filtering

Sampai di mana kita pada tahapan Model Development menggunakan metode Based Filtering.

In [46]:
data = movie_new
data.sample(10)

,review_users,movie,genre
293,294.0,Mad Max 2: The Road Warrior,Action|Adventure|Sci-Fi|Thriller
381,383.0,Red Dawn,Action|Drama|War
746,904.0,Frozen,Adventure|Animation|Comedy|Family|Fantasy|Musical
602,644.0,The Black Dahlia,Crime|Drama|Mystery|Thriller
365,367.0,Lilo & Stitch,Adventure|Animation|Comedy|Drama|Family|Fantas...
375,377.0,Moonrise Kingdom,Adventure|Comedy|Drama|Romance
363,365.0,Glory,Drama|History|War
433,436.0,The Equalizer,Action|Crime|Thriller
713,836.0,Boyhood,Drama
508,527.0,Captain Phillips,Biography|Drama|Thriller

Kita membuat variable baru bernama **data** lalu melihat sample acak sebanyak 10 baris.

Kita akan membangun model sistem rekomendasi sederhana film berdasarkan genrenya, teknik yang kita gunakan adalah dengan TF-IDF Vectorizer.

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer
 
# Inisialisasi TfidfVectorizer
tf = TfidfVectorizer()
 
# Melakukan perhitungan idf pada data genre
tf.fit(data['genre']) 
 
tf.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['action',
 'adventure',
 'animation',
 'biography',
 'comedy',
 'crime',
 'documentary',
 'drama',
 'family',
 'fantasy',
 'fi',
 'history',
 'horror',
 'music',
 'musical',
 'mystery',
 'romance',
 'sci',
 'sport',
 'thriller',
 'war',
 'western']

Kemudian kita fit_tranform data genre dalam bentuk matrik.

In [48]:
# Melakukan fit lalu ditransformasikan ke bentuk matrix
tfidf_matrix = tf.fit_transform(data['genre']) 
 
# Melihat ukuran matrix tfidf
tfidf_matrix.shape

(954, 22)

Kita bisa melihatnya dengan fungsi todense()

In [49]:
# Mengubah vektor tf-idf dalam bentuk matriks dengan fungsi todense()
tfidf_matrix.todense()

matrix([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.47834689, 0.        , 0.        , ..., 0.47399518, 0.        ,
         0.        ],
        [0.4734089 , 0.51386057, 0.        , ..., 0.        , 0.        ,
         0.        ]])

Selanjutnya, kita akan lihat matriks tf-idf untuk beberapa nama film dan kategori genrenya

In [50]:
# Membuat dataframe untuk melihat tf-idf matrix
 
pd.DataFrame(
    tfidf_matrix.todense(), 
    columns=tf.get_feature_names(),
    index=data.movie
).sample(22, axis=1).sample(10, axis=0)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,mystery,western,sport,family,fantasy,crime,music,thriller,documentary,action,...,biography,horror,adventure,romance,comedy,fi,sci,history,musical,animation
movie,,,,,,,,,,,,,,,,,,,,,
Diary of a Mad Black Woman,0.000000,0.0,0.0,0.0000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.688798,0.580974,0.000000,0.000000,0.000000,0.0,0.0
Pale Rider,0.000000,1.0,0.0,0.0000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
What Dreams May Come,0.000000,0.0,0.0,0.0000,0.642704,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.648340,0.000000,0.000000,0.000000,0.000000,0.0,0.0
Miracle at St. Anna,0.000000,0.0,0.0,0.0000,0.000000,0.469945,0.0,0.353827,0.0,0.357075,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
King Kong,0.000000,0.0,0.0,0.0000,0.000000,0.000000,0.0,0.000000,0.0,0.471896,...,0.0,0.0,0.512218,0.607282,0.000000,0.000000,0.000000,0.000000,0.0,0.0
Ghost Rider,0.000000,0.0,0.0,0.0000,0.671490,0.000000,0.0,0.521576,0.0,0.526364,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
Killer Joe,0.000000,0.0,0.0,0.0000,0.000000,0.587026,0.0,0.441978,0.0,0.000000,...,0.0,0.0,0.000000,0.574003,0.000000,0.000000,0.000000,0.000000,0.0,0.0
The Hurt Locker,0.000000,0.0,0.0,0.0000,0.000000,0.000000,0.0,0.332838,0.0,0.000000,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.650666,0.0,0.0
Red Planet,0.000000,0.0,0.0,0.0000,0.000000,0.000000,0.0,0.439843,0.0,0.443881,...,0.0,0.0,0.000000,0.000000,0.000000,0.552045,0.552045,0.000000,0.0,0.0
Harry Potter and the Chamber of Secrets,0.529872,0.0,0.0,0.5841,0.468295,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.398451,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0

Kita bisa lihat hasil di atas, sebagai contoh pada film Grown Ups memiliki sekitar 1.0 bergenre Comedy.

Dari sini kita sudah berhasil merepresantasikan fitur penting pada kategori genre, dan menunjukan korelasi film terhadap genrenya.

Kemudian kita akan menghitung derajat kesamaan antar film dengan teknik Cosine Similarity, kita akan menggunakan library scikit-learn untuk menggunakan teknik Cosine Similarity

In [51]:
from sklearn.metrics.pairwise import cosine_similarity
 
# Menghitung cosine similarity pada matrix tf-idf
genre_sim = cosine_similarity(tfidf_matrix) 
genre_sim

array([[1.        , 0.        , 0.28987898, ..., 0.15195737, 0.11233677,
        0.11117712],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.60393419],
       [0.28987898, 0.        , 1.        , ..., 0.52420967, 0.38752989,
        0.38352942],
       ...,
       [0.15195737, 0.        , 0.52420967, ..., 1.        , 0.73926506,
        0.20104983],
       [0.11233677, 0.        , 0.38752989, ..., 0.73926506, 1.        ,
        0.37508279],
       [0.11117712, 0.60393419, 0.38352942, ..., 0.20104983, 0.37508279,
        1.        ]])

Kemudian kita akan melihat hasil dari kesamaan antar film yang telah kita lakukan pada teknik Cosine Similarity.

In [52]:
# Membuat dataframe dari variabel cosine_sim dengan baris dan kolom berupa nama film
genre_sim_df = pd.DataFrame(genre_sim, index=data['movie'], columns=data['movie'])
print('Shape:', genre_sim_df.shape)
 
# Melihat similarity matrix pada setiap film
genre_sim_df.sample(5, axis=1).sample(10, axis=0)

Shape: (954, 954)

movie,Underworld: Evolution,Cloud Atlas,Ant-Man,Snakes on a Plane,Sicario
movie,,,,,
Cinderella,0.227879,0.133232,0.000000,0.109528,0.101555
Click,0.256249,0.149819,0.205064,0.123163,0.114198
Michael Clayton,0.149767,0.145133,0.000000,0.612674,0.919269
Charlie St. Cloud,0.292061,0.170757,0.000000,0.140376,0.130158
Lars and the Real Girl,0.000000,0.181413,0.248307,0.149136,0.138280
The Blair Witch Project,0.000000,0.000000,0.000000,0.000000,0.000000
American Psycho,0.000000,0.219312,0.000000,0.656098,0.608339
The Game Plan,0.000000,0.000000,0.159180,0.000000,0.000000
Hamlet 2,0.000000,0.000000,0.188620,0.000000,0.000000
Avatar,0.935634,0.608199,0.790271,0.352056,0.149862

Yang perlu di perhatikan kenapa kesamaan nya tidak mencapai angka 1.0 adalah karena kita memiliki film dengan genre lebih dari satu. Namun kalau kita mencoba mencari secara lengkap ada film dengan kesamaan 1.0. 

Jadi kita coba merekomendasikan sebuah film kepada Users berdasarkan genrenya, dan sebuah genre pun bermacam macam.

## Melihat Hasil Rekomendasi

In [53]:
def film_recommendations(nama_movie, similarity_data=genre_sim_df, items=data[['movie', 'genre']], k=5):
    
    index = similarity_data.loc[:,nama_movie].to_numpy().argpartition(
        range(-1, -k, -1))
    
    closest = similarity_data.columns[index[-1:-(k+2):-1]]
    closest = closest.drop(nama_movie, errors='ignore')
 
    return pd.DataFrame(closest).merge(items).head(k)

Kita akan coba masukan film Avatar, jika kita lihat Avatar memiliki 4 genre yaitu Action, Adventure, Fantasy, dan Sci-Fi. Kita akan mencoba merekomdasikan sebuah film dari genre tersebut.

In [54]:
data[data.movie.eq('Avatar')]

     review_users   movie                            genre
944        3054.0  Avatar  Action|Adventure|Fantasy|Sci-Fi

In [55]:
film_recommendations('Avatar')

,movie,genre
0,Star Wars: Episode VI - Return of the Jedi,Action|Adventure|Fantasy|Sci-Fi
1,The Amazing Spider-Man 2,Action|Adventure|Fantasy|Sci-Fi
2,Man of Steel,Action|Adventure|Fantasy|Sci-Fi
3,Star Wars: Episode III - Revenge of the Sith,Action|Adventure|Fantasy|Sci-Fi
4,Highlander: Endgame,Action|Adventure|Fantasy|Sci-Fi

Menarik! Ternyata ada film dengan 4 genre yang sama, tentu dengan nama film yang berbeda. Jadi kita akan merekomendasikan film tersebut kepada Users, barangkali tertarik.